name: ps
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pandas
  - ca-certificates
  - openssl
  - pytest
  - pytest-datadir
  - tqdm
  - langcodes
  - beautifulsoup4
  - lxml
  # Dev dependencies:
  - black
  - flake8
  - flake8-isort
  - flake8-docstrings
  - flake8-bugbear
  - flake8-rst-docstrings
  - darglint
