name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
          cache: "pipenv"
      - name: Install Pipenv
        run: python -m pip install --upgrade pipenv wheel
      - name: Install Python dependencies
        run: pipenv install --deploy --dev
      - name: Lint with Black
        run: pipenv run black --check .
      - name: Lint with Flake8
        run: pipenv run flake8 .
      - name: Tests
        run: pipenv run pytest
